Traceback (most recent call last):
  File "./trace_debug.py", line 4, in <module>
    raise Exception('this is manual')
Exception: this is manual
